apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secret-staging
  namespace: staging
type: Opaque # or kubernetes.io/ вашу-тип-секрета
data:
  # Encode your sensitive data in Base64
  # Example (replace with your actual base64 encoded database URL):
  # DATABASE_URL: "cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAaG9zdDpwb3J0L2RibmFtZQ=="
  DATABASE_URL: "<base64_encoded_database_url_staging>"
  # Add other sensitive configuration here, base64 encoded
