apiVersion: v1
kind: Service
metadata:
  name: flask-app-staging
  namespace: staging
  labels:
    app: flask-app
    env: staging
spec:
  selector:
    app: flask-app
    env: staging
  ports:
    - protocol: TCP
      port: 80 # Port the service listens on
      targetPort: 8000 # Port the container listens on
  type: ClusterIP # Or NodePort, LoadBalancer depending on your needs
